### PR TITLE
Add scoring board and scoring system based on successful PR merges.

### PR DESCRIPTION
**Pull request by yizongk**
Very ugly display of the scoreboard though, would love for someone that is good with css to mess with it.

### CODE REVIEW

**Comment by yizongk** [comment]
fixes #68

**Comment by yizongk** [comment]
fixes Issue #70

**Comment by Fioringo** [comment]
Currently under review.

Something I noticed from reading the code is that your imports of your components contain `path/component.js`. You don't need the `.js` part, but that's trivial.

**Comment by Gutierrezjdr** [comment]
image

This is what I see. Is this what you are looking for?

**Comment by yizongk** [comment]
> You don't nee

Ya, it's just a force of habits, I will remove it

**Pull request merged**
